### ISSUE TITLE
Formatting logger message sometimes breaks whole logging

### ISSUE THREAD

**Issue by DevRayy** [KNTGPolygon/PolyEngine#116]
This occured to me when I tried to add some more debug logging, and it didn't show up on my console. The log ended on some SoundResource log message
```gConsole.LogDebug("Bitstream is {} channel, {}Hz", vorbisInfo.channels, vorbisInfo.rate);```
But it was not printed fully, it had some random characters instead of vorbisInfo.channels, and nothing more, no more log messages were printed. I commented out this line (and few others from MeshResource and FontResource), and logging started working as a charm.

Happened on Ubuntu 17.10 using Terminator terminal emulator.

**Comment by MuniuDev** [comment]
I belive this is now fixed.
